### ISSUE TITLE
Cannot find type definition file for babel__core (plugin-structure-mongoose) [EDIT: Pull Request Fix Within]

### ISSUE THREAD

**Issue by dylanh724** [open-devs/fastify-typescript-generator#17]
Heads up, just generator in an empty dir and got this with `plugin-structure-mongoose`:

![image](https://user-images.githubusercontent.com/8840024/109387933-03e26000-793f-11eb-81a9-6a7b3be6a2e4.png)

> /sba2 == root
![image](https://user-images.githubusercontent.com/8840024/109387926-fc22bb80-793e-11eb-8388-0d8e8c90b5a0.png)

Ubuntu 20.04

**Comment by dylanh724** [comment]
Adding the following to package.json's `devDependencies`:
```json
"@types/babel__core": "^7.1.12"
```
seemed to do the trick. However, this is a workaround: Someone with more time should make a pull request.

**Comment by dylanh724** [comment]
Actually, I got this: https://github.com/open-devs/fastify-typescript-generator/pull/18

**Comment by dylanh724** [comment]
Eh, there are a ton of typings missing. Is this repo still maintained?
![image](https://user-images.githubusercontent.com/8840024/109388393-b287a000-7941-11eb-966f-80269a2942a3.png)

**Comment by MiKr13** [comment]
sorry for late response.

**Comment by MiKr13** [comment]
Though we haven't been able to verify it in long time.

If you can help with this, we would really appreciate that. Or I'll add the types package by this month's end.

**Comment by MiKr13** [comment]
I am not sure why it's there as types/node is included.

**Comment by MiKr13** [comment]
I'll get back on it today.

**Comment by MiKr13** [comment]
Hi @dylanh724 we have updated the dependencies as well as added the missing types, it's weird that initially, it didn't show any sorts of errors to us when it tested every template out. But thanks a lot for pointing it out. 

**Please Note fastify don't have a type definition file & it's out of scope of this project**
